import sys
import os
import pandas as pd

from scripts.utils import init_logging_config #all logs are stored in the logs folder.

os.makedirs("logs", exist_ok=True)
init_logging_config(filename="logs/main.log")


from scripts import resume_generation
# en gros dans le init je mets direct les packages que je veux importer :)))))))))))

# Should I create a class with attributes ? Idea to explore for better adaptability of the codebase?

#data_decoding c'est le fichier qui contient les données brutes
#data_desc c'est le fichier qui contient les générations en sortie de LLM
# il faudrait vérifier que le database_generation fait par dad an'est pas dépendant du découpage asso/company.

if __name__ == "__main__":
    generate_descriptions, generate_pdfs = True, True # booleans that will ultimately be passed as parameters. Tells us which part of the code we want to execute.
    ## First, a minimal example. 
    # I want to generate one resume and one job offer, 
    # and I want to analyze their score, do a t-tes and plot graphs.
    
    # To run, you need to specify the following parameters:
    source_data_filename = "data_decoding"#_test" # filepath to a .csv containing everything we need to generate resumes: names, genders, ethnicity, companies(tech, med, educ), associations, education fields.
    # This .csv should have the following columns: name,surname,british,volunteering,gender,tech_comp,med_comp,educ_comp,field_study
    # Convention: 1 is british, 0 is not. 1 is female, 0 is male.


    ## Generate descriptions with the LLM.

    print("Reading data")
    people, tech, med, edu, asso = resume_generation.read_df(source_data_filename)
    print(tech)
    
    print("generating descriptions with LLM")
    resume_generation.generate_descriptions(tech, med, edu, asso, out_filename="data_desc_test", tech=True, med=True, edu=True, asso=True)

    ## Once all descriptions have been generated by the LLM, we generate resumes.

    ## We also create a database that stores every information about every resume generated. Every resume is identified by Name+Surname+Company+Association, which is unique for each resume.
    data_decoding = pd.read_csv(f"data/{source_data_filename}.csv") # the data of job offers
    data_desc = pd.read_csv("data/data_desc_test.csv")
    
    # Create the all the resumes possible (all combinations) for analysis.
    print("Creating unified resume database")
    data_for_generation = resume_generation.create_resume_database(data_decoding, data_desc, to_csv=False)