import sys
import pandas as pd

from scripts import resume_generation
# en gros dans le init je mets direct les packages que je veux importer :)))))))))))

# Should I create a class with attributes ? Idea to explore for better adaptability of the codebase?

if __name__ == "__main__":
    ## First, a minimal example. 
    # I want to generate one resume and one job offer, 
    # and I want to analyze their score, do a t-tes and plot graphs.
    
    # To run, you need to specify the following parameters:
    source_dat_filename = sys.argv[1] # filepath to a .csv containing everything we need to generate resumes: names, genders, ethnicity, companies(tech, med, educ), associations, education fields.
    # This .csv should have the following columns: name,surname,british,volunteering,gender,tech_comp,med_comp,educ_comp,field_study
    # Convention: 1 is british, 0 is not. 1 is female, 0 is male.

    print(source_dat_filename)

    ## Generate descriptions with the LLM.

    people, tech, med, edu, asso = resume_generation.read_df(source_dat_filename)

    resume_generation.generate_descriptions(tech, med, edu, asso, tech=True, med=True, edu=True, asso=True)

    ## Once all descriptions have been generated by the LLM, we generate resumes.

    ## We also create a database that stores every information about every resume generated. Every resume is identified by Name+Surname+Company+Association, which is unique for each resume.
    data_decoding = pd.read_csv(sys.argv[1]) # the data of job offers
    data_desc = pd.read_csv(sys.argv[2]) # the data of job descriptions
    
    # Create the all the resumes possible (all combinations) for analysis.
    data_for_generation = create_resume_database(data_decoding, data_desc, to_csv=False)